name: Build and Push to K3s Registry

on:
  push:
    branches: 
      - '**'                          

permissions:
  contents: read
  packages: write

env:
  REGISTRY: k3d-mycluster-registry:34789
  IMAGE_NAME: iris_analysis

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: |
          # Derive branch name from GITHUB_REF
          echo "branch=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"
        # GITHUB_REF includes refs/heads/<branch> :contentReference[oaicite:3]{index=3}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Log in to K3s registry
      #   run: |
      #     echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ env.REGISTRY }} \
      #       --username "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
      #   # Store your registry credentials as secrets: REGISTRY_USERNAME and REGISTRY_PASSWORD :contentReference[oaicite:4]{index=4}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.extract_branch.outputs.branch }}
        # Uses branch name as tag :contentReference[oaicite:5]{index=5}

      - name: Verify pushed images
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.extract_branch.outputs.branch }}
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        # Optional validation step :contentReference[oaicite:6]{index=6}
