name: Build and Push to K3s Registry

on:
  push:
    branches:
      - '**'  # Trigger on all branches

permissions:
  contents: read
  packages: write

env:
  REGISTRY: irfanmu93
  IMAGE_NAME: iris_analysis

jobs:
  build-and-push:
    runs-on: [self-hosted, Linux, X64]  # Use the custom label

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:qemu-v8.1.5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to docker registry
        run: |
          echo "${{ secrets.REGISTRY_PAT }}" | docker login \
            --username "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Push and verify image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.extract_branch.outputs.branch }} .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.extract_branch.outputs.branch }}
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.extract_branch.outputs.branch }}
